[theme]
primaryColor = "#3C1E1E"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "맑은 고딕"

[server]
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false 